declare const appConfig: import("tamagui").TamaguiInternalConfig<{
    color: {
        white: import("@tamagui/web").Variable<string>;
        black: import("@tamagui/web").Variable<string>;
        brandPrimary: import("@tamagui/web").Variable<string>;
        brand50: import("@tamagui/web").Variable<string>;
        brand100: import("@tamagui/web").Variable<string>;
        brand200: import("@tamagui/web").Variable<string>;
        brand300: import("@tamagui/web").Variable<string>;
        brand400: import("@tamagui/web").Variable<string>;
        brand500: import("@tamagui/web").Variable<string>;
        brand600: import("@tamagui/web").Variable<string>;
        brand700: import("@tamagui/web").Variable<string>;
        brand800: import("@tamagui/web").Variable<string>;
        brand900: import("@tamagui/web").Variable<string>;
        neutral50: import("@tamagui/web").Variable<string>;
        neutral100: import("@tamagui/web").Variable<string>;
        neutral200: import("@tamagui/web").Variable<string>;
        neutral300: import("@tamagui/web").Variable<string>;
        neutral400: import("@tamagui/web").Variable<string>;
        neutral500: import("@tamagui/web").Variable<string>;
        neutral600: import("@tamagui/web").Variable<string>;
        neutral700: import("@tamagui/web").Variable<string>;
        neutral800: import("@tamagui/web").Variable<string>;
        neutral900: import("@tamagui/web").Variable<string>;
        error50: import("@tamagui/web").Variable<string>;
        error100: import("@tamagui/web").Variable<string>;
        error200: import("@tamagui/web").Variable<string>;
        error300: import("@tamagui/web").Variable<string>;
        error400: import("@tamagui/web").Variable<string>;
        error500: import("@tamagui/web").Variable<string>;
        error600: import("@tamagui/web").Variable<string>;
        error700: import("@tamagui/web").Variable<string>;
        error800: import("@tamagui/web").Variable<string>;
        error900: import("@tamagui/web").Variable<string>;
        warning50: import("@tamagui/web").Variable<string>;
        warning100: import("@tamagui/web").Variable<string>;
        warning200: import("@tamagui/web").Variable<string>;
        warning300: import("@tamagui/web").Variable<string>;
        warning400: import("@tamagui/web").Variable<string>;
        warning500: import("@tamagui/web").Variable<string>;
        warning600: import("@tamagui/web").Variable<string>;
        warning700: import("@tamagui/web").Variable<string>;
        warning800: import("@tamagui/web").Variable<string>;
        warning900: import("@tamagui/web").Variable<string>;
        success50: import("@tamagui/web").Variable<string>;
        success100: import("@tamagui/web").Variable<string>;
        success200: import("@tamagui/web").Variable<string>;
        success300: import("@tamagui/web").Variable<string>;
        success400: import("@tamagui/web").Variable<string>;
        success500: import("@tamagui/web").Variable<string>;
        success600: import("@tamagui/web").Variable<string>;
        success700: import("@tamagui/web").Variable<string>;
        success800: import("@tamagui/web").Variable<string>;
        success900: import("@tamagui/web").Variable<string>;
    };
    space: {
        0: import("@tamagui/web").Variable<number>;
        0.25: import("@tamagui/web").Variable<number>;
        0.5: import("@tamagui/web").Variable<number>;
        0.75: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        1.5: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        2.5: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        3.5: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        true: import("@tamagui/web").Variable<number>;
        4.5: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        11: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        13: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        15: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        17: import("@tamagui/web").Variable<number>;
        18: import("@tamagui/web").Variable<number>;
        19: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
        [-0.25]: import("@tamagui/web").Variable<number>;
        [-0.5]: import("@tamagui/web").Variable<number>;
        [-0.75]: import("@tamagui/web").Variable<number>;
        [-1]: import("@tamagui/web").Variable<number>;
        [-1.5]: import("@tamagui/web").Variable<number>;
        [-2]: import("@tamagui/web").Variable<number>;
        [-2.5]: import("@tamagui/web").Variable<number>;
        [-3]: import("@tamagui/web").Variable<number>;
        [-3.5]: import("@tamagui/web").Variable<number>;
        [-4]: import("@tamagui/web").Variable<number>;
        "-true": import("@tamagui/web").Variable<number>;
        [-4.5]: import("@tamagui/web").Variable<number>;
        [-5]: import("@tamagui/web").Variable<number>;
        [-6]: import("@tamagui/web").Variable<number>;
        [-7]: import("@tamagui/web").Variable<number>;
        [-8]: import("@tamagui/web").Variable<number>;
        [-9]: import("@tamagui/web").Variable<number>;
        [-10]: import("@tamagui/web").Variable<number>;
        [-11]: import("@tamagui/web").Variable<number>;
        [-12]: import("@tamagui/web").Variable<number>;
        [-13]: import("@tamagui/web").Variable<number>;
        [-14]: import("@tamagui/web").Variable<number>;
        [-15]: import("@tamagui/web").Variable<number>;
        [-16]: import("@tamagui/web").Variable<number>;
        [-17]: import("@tamagui/web").Variable<number>;
        [-18]: import("@tamagui/web").Variable<number>;
        [-19]: import("@tamagui/web").Variable<number>;
        [-20]: import("@tamagui/web").Variable<number>;
    };
    size: {
        0: import("@tamagui/web").Variable<number>;
        0.25: import("@tamagui/web").Variable<number>;
        0.5: import("@tamagui/web").Variable<number>;
        0.75: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        1.5: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        2.5: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        3.5: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        true: import("@tamagui/web").Variable<number>;
        4.5: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        11: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
        13: import("@tamagui/web").Variable<number>;
        14: import("@tamagui/web").Variable<number>;
        15: import("@tamagui/web").Variable<number>;
        16: import("@tamagui/web").Variable<number>;
        17: import("@tamagui/web").Variable<number>;
        18: import("@tamagui/web").Variable<number>;
        19: import("@tamagui/web").Variable<number>;
        20: import("@tamagui/web").Variable<number>;
    };
    radius: {
        0: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        true: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
        6: import("@tamagui/web").Variable<number>;
        7: import("@tamagui/web").Variable<number>;
        8: import("@tamagui/web").Variable<number>;
        9: import("@tamagui/web").Variable<number>;
        10: import("@tamagui/web").Variable<number>;
        11: import("@tamagui/web").Variable<number>;
        12: import("@tamagui/web").Variable<number>;
    };
    zIndex: {
        0: import("@tamagui/web").Variable<number>;
        1: import("@tamagui/web").Variable<number>;
        2: import("@tamagui/web").Variable<number>;
        3: import("@tamagui/web").Variable<number>;
        4: import("@tamagui/web").Variable<number>;
        5: import("@tamagui/web").Variable<number>;
    };
} & Omit<{
    color: {
        white: import("@tamagui/web").Variable<string>;
        black: import("@tamagui/web").Variable<string>;
        brandPrimary: import("@tamagui/web").Variable<string>;
        brand50: import("@tamagui/web").Variable<string>;
        brand100: import("@tamagui/web").Variable<string>;
        brand200: import("@tamagui/web").Variable<string>;
        brand300: import("@tamagui/web").Variable<string>;
        brand400: import("@tamagui/web").Variable<string>;
        brand500: import("@tamagui/web").Variable<string>;
        brand600: import("@tamagui/web").Variable<string>;
        brand700: import("@tamagui/web").Variable<string>;
        brand800: import("@tamagui/web").Variable<string>;
        brand900: import("@tamagui/web").Variable<string>;
        neutral50: import("@tamagui/web").Variable<string>;
        neutral100: import("@tamagui/web").Variable<string>;
        neutral200: import("@tamagui/web").Variable<string>;
        neutral300: import("@tamagui/web").Variable<string>;
        neutral400: import("@tamagui/web").Variable<string>;
        neutral500: import("@tamagui/web").Variable<string>;
        neutral600: import("@tamagui/web").Variable<string>;
        neutral700: import("@tamagui/web").Variable<string>;
        neutral800: import("@tamagui/web").Variable<string>;
        neutral900: import("@tamagui/web").Variable<string>;
        error50: import("@tamagui/web").Variable<string>;
        error100: import("@tamagui/web").Variable<string>;
        error200: import("@tamagui/web").Variable<string>;
        error300: import("@tamagui/web").Variable<string>;
        error400: import("@tamagui/web").Variable<string>;
        error500: import("@tamagui/web").Variable<string>;
        error600: import("@tamagui/web").Variable<string>;
        error700: import("@tamagui/web").Variable<string>;
        error800: import("@tamagui/web").Variable<string>;
        error900: import("@tamagui/web").Variable<string>;
        warning50: import("@tamagui/web").Variable<string>;
        warning100: import("@tamagui/web").Variable<string>;
        warning200: import("@tamagui/web").Variable<string>;
        warning300: import("@tamagui/web").Variable<string>;
        warning400: import("@tamagui/web").Variable<string>;
        warning500: import("@tamagui/web").Variable<string>;
        warning600: import("@tamagui/web").Variable<string>;
        warning700: import("@tamagui/web").Variable<string>;
        warning800: import("@tamagui/web").Variable<string>;
        warning900: import("@tamagui/web").Variable<string>;
        success50: import("@tamagui/web").Variable<string>;
        success100: import("@tamagui/web").Variable<string>;
        success200: import("@tamagui/web").Variable<string>;
        success300: import("@tamagui/web").Variable<string>;
        success400: import("@tamagui/web").Variable<string>;
        success500: import("@tamagui/web").Variable<string>;
        success600: import("@tamagui/web").Variable<string>;
        success700: import("@tamagui/web").Variable<string>;
        success800: import("@tamagui/web").Variable<string>;
        success900: import("@tamagui/web").Variable<string>;
    };
    space: {
        0: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.25: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.75: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        true: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        6: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        7: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        8: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        9: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        10: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        11: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        12: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        13: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        14: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        15: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        16: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        17: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        18: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        19: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        20: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-0.25]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-0.5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-0.75]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-1]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-1.5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-2]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-2.5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-3]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-3.5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-4]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        "-true": import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-4.5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-5]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-6]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-7]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-8]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-9]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-10]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-11]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-12]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-13]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-14]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-15]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-16]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-17]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-18]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-19]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        [-20]: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
    };
    size: {
        0: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.25: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        0.75: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        true: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4.5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        6: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        7: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        8: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        9: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        10: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        11: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        12: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        13: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        14: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        15: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        16: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        17: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        18: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        19: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        20: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
    };
    radius: {
        0: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        true: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        6: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        7: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        8: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        9: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        10: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        11: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        12: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
    };
    zIndex: {
        0: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        1: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        2: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        3: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        4: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        5: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
    };
    icon: {
        sm: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        md: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
        lg: import("@tamagui/web").Variable<import("@tamagui/web").Variable<number>>;
    };
}, "color" | "space" | "size" | "radius" | "zIndex">, {
    light_brand: import("tamagui").TamaguiBaseTheme;
    dark_brand: import("tamagui").TamaguiBaseTheme;
}, import("@tamagui/web").GenericShorthands, {
    [key: string]: {
        [key: string]: string | number;
    };
}, {
    [key: string]: string | any[] | {
        [key: string]: any;
    };
}, import("@tamagui/web").GenericFonts, boolean | undefined, string | undefined, {
    allowedStyleValues?: ((boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web") | {
        space?: ("number" | (boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web") | "percent") | undefined;
        size?: ("number" | (boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web") | "percent") | undefined;
        radius?: ("number" | (boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web")) | undefined;
        zIndex?: ("number" | (boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web")) | undefined;
        color?: ((boolean | "strict" | "somewhat-strict" | "strict-web" | "somewhat-strict-web") | "named") | undefined;
    }) | undefined;
    autocompleteSpecificTokens?: (boolean | "except-special") | undefined;
    mediaPropOrder?: boolean | undefined;
    fastSchemeChange?: boolean | undefined;
}>;
export type AppConfig = typeof appConfig;
declare module "tamagui" {
    interface TamaguiCustomConfig extends AppConfig {
    }
}
export default appConfig;
//# sourceMappingURL=tamagui.config.d.ts.map